language: java
jdk:
  - oraclejdk8

sudo: required

before_install:
  - docker run --name redis-integration-test-db -p 6378:6379 -d redis

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

jobs:
  include:
  - stage: build
    if: branch = master
    script: ./gradlew build
  - stage: buildImage
    script: docker build .

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  provider: elasticbeanstalk
  script: ./gradlew build
  region: "eu-west-2"
  app: "docker-app"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-eu-west-2-160364560450"
  bucket_path: "docker-app"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"