version: '3'
services:
  redis-db:
    container_name: redis-db-container
    image: redis
    ports:
      - "6379:6379"
  study-web-app:
    restart: always
    container_name: docker-app-container
    depends_on:
      - redis-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./build/libs/docker-app.jar:/usr/app/application.jar
